spring:
  application:
    name: Library API
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

springdoc:
  override-with-generic-response: false

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        dan7arievlis: trace
    org:
      springframework:
        web: debug
        security: trace

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'